#setting up 
library(rtweet)
library(rbind)
library(dplyr)
library(tidytext)
library(stringr)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(textmining)
library(rio)
library(quanteda)
library(xml2)
library(ggplot2)
library(tidyverse)
library(reshape2)

